[profile.default]
src = "src"
test = "test"
script = "script"
out = "out"
cache_path = "cache"
libs = ["../lib"]
solc_version = "0.8.26"
optimizer = true
optimizer_runs = 200
via_ir = true
evm_version = "cancun"

[fmt]
line_length = 100
tab_width = 4
bracket_spacing = true
int_types = "long"

[invariant]
runs = 256
depth = 64
fail_on_revert = false
